package com.saleh.smsaccounting;
import android.Manifest;import android.app.*;import android.os.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.net.Uri;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout root,list; Db db; TextView balance,inOut; final int SMS=20;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);db=new Db(this);build();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS},SMS);}
 TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(20,16,20,16);return t;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18); ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(tv("محاسبة رسائل SMS",25));balance=tv("",22);root.addView(balance);inOut=tv("",16);root.addView(inOut);Button open=new Button(this);open.setText("تعيين الرصيد الافتتاحي");open.setOnClickListener(v->opening());root.addView(open);Button scan=new Button(this);scan.setText("استيراد وتحليل الرسائل المالية");scan.setOnClickListener(v->scan());root.addView(scan);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);refresh();}
 void opening(){final EditText e=new EditText(this);e.setInputType(2|8192);e.setHint("مثال: 100000");new AlertDialog.Builder(this).setTitle("الرصيد الافتتاحي").setMessage("هذا الرصيد هو نقطة بداية الحساب، ولن يتم استبداله برصيد الرسائل.").setView(e).setPositiveButton("حفظ",(d,w)->{try{db.setOpening(Double.parseDouble(e.getText().toString()));refresh();}catch(Exception x){}}).setNegativeButton("إلغاء",null).show();}
 void scan(){if(checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.READ_SMS},SMS);return;}Cursor c=getContentResolver().query(Uri.parse("content://sms/inbox"),new String[]{"body","date"},null,null,"date ASC");int n=0;if(c!=null){while(c.moveToNext()){String body=c.getString(0);SmsAnalyzer.Result r=SmsAnalyzer.analyze(body);if(!r.type.equals("unknown")&&r.amount>0){n+=db.add(new Transaction(0,r.type,r.party,r.reference,body,r.amount,r.smsBalance,c.getLong(1)))>0?1:0;}}c.close();}refresh();Toast.makeText(this,"تم تحليل "+n+" رسالة جديدة",Toast.LENGTH_LONG).show();}
 void refresh(){list.removeAllViews();double bal=db.opening(),in=0,out=0;for(Transaction t:db.all()){if(t.type.equals("credit")){bal+=t.amount;in+=t.amount;}else{bal-=t.amount;out+=t.amount;}t.calculatedBalance=bal;TextView row=tv((t.type.equals("credit")?"دائن +":"مدين -")+" "+t.amount+"  |  "+t.party+"\nالرصيد المحسوب: "+bal+(t.smsBalance>0?"  | رصيد الرسالة: "+t.smsBalance:""),16);list.addView(row);View line=new View(this);line.setBackgroundColor(0xffdddddd);list.addView(line,new LinearLayout.LayoutParams(-1,1));}balance.setText("الرصيد المحسوب: "+bal);inOut.setText("إجمالي الداخل: "+in+"    |    إجمالي الخارج: "+out);}
}
