package com.saleh.smsaccounting;
import android.Manifest;import android.app.*;import android.os.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.net.Uri;import android.provider.Telephony;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout root,list;Db db;TextView balance,inOut;final int SMS=20;String selectedConversation=null;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setLayoutDirection(View.LAYOUT_DIRECTION_RTL);db=new Db(this);build();if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS},SMS);}
 TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(20,14,20,14);return t;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,16);ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);
 root.addView(tv("محاسبة رسائل SMS",25));balance=tv("",22);root.addView(balance);inOut=tv("",16);root.addView(inOut);
 Button manual=new Button(this);manual.setText("➕ إدخال عملية يدوية");manual.setOnClickListener(v->manual());root.addView(manual);
 Button conv=new Button(this);conv.setText("📥 استيراد من محادثة SMS محددة");conv.setOnClickListener(v->chooseConversation());root.addView(conv);
 Button all=new Button(this);all.setText("📋 عرض كل العمليات");all.setOnClickListener(v->{selectedConversation=null;refresh();});root.addView(all);
 Button scan=new Button(this);scan.setText("🔄 تحليل كل الرسائل المالية");scan.setOnClickListener(v->scanAll());root.addView(scan);
 Button review=new Button(this);review.setText("⚠️ العمليات التي تحتاج مراجعة");review.setOnClickListener(v->showReviews());root.addView(review);
 Button open=new Button(this);open.setText("تعيين الرصيد الافتتاحي");open.setOnClickListener(v->opening());root.addView(open);
 sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);refresh();}
 void opening(){final EditText e=new EditText(this);e.setInputType(2|8192);e.setHint("مثال: 100000");new AlertDialog.Builder(this).setTitle("الرصيد الافتتاحي").setMessage("نقطة بداية الحساب فقط، ولا يتم استبدالها برصيد الرسائل.").setView(e).setPositiveButton("حفظ",(d,w)->{try{db.setOpening(Double.parseDouble(e.getText().toString()));refresh();}catch(Exception x){}}).setNegativeButton("إلغاء",null).show();}
 void manual(){LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"مدين / خصم","دائن / إيداع"}));EditText party=new EditText(this);party.setHint("اسم الشخص / الجهة");EditText amount=new EditText(this);amount.setHint("المبلغ");amount.setInputType(2|8192);EditText note=new EditText(this);note.setHint("البيان / الملاحظة");f.addView(type);f.addView(party);f.addView(amount);f.addView(note);new AlertDialog.Builder(this).setTitle("إدخال عملية يدوية").setView(f).setPositiveButton("حفظ",(d,w)->{try{double a=Double.parseDouble(amount.getText().toString());if(a<=0)throw new Exception();String t=type.getSelectedItemPosition()==0?"debit":"credit";db.add(new Transaction(0,t,party.getText().toString().trim(),"",note.getText().toString(),a,0,System.currentTimeMillis(),"يدوي"));refresh();}catch(Exception e){Toast.makeText(this,"أدخل مبلغًا صحيحًا",Toast.LENGTH_SHORT).show();}}).setNegativeButton("إلغاء",null).show();}
 void chooseConversation(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_SMS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.READ_SMS},SMS);return;}final LinkedHashMap<String,ArrayList<String>> groups=new LinkedHashMap<>();Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"address"},null,null,"date DESC");if(c!=null){while(c.moveToNext()){String a=c.getString(0);if(a==null||a.trim().isEmpty())a="غير معروف";if(!groups.containsKey(a))groups.put(a,new ArrayList<>());}c.close();}if(groups.isEmpty()){Toast.makeText(this,"لا توجد رسائل SMS",Toast.LENGTH_SHORT).show();return;}String[] names=groups.keySet().toArray(new String[0]);final int[] selected={-1}; new AlertDialog.Builder(this).setTitle("اختر محادثة واحدة فقط").setSingleChoiceItems(names,-1,(d,which)->{selected[0]=which;}).setPositiveButton("اختيار هذه المحادثة",(d,w)->{if(selected[0]<0){Toast.makeText(this,"اختر محادثة واحدة أولاً",Toast.LENGTH_SHORT).show();return;}importConversation(names[selected[0]]);}).setNegativeButton("إلغاء",null).show();}
 void importConversation(String address){Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"address","body","date"}, "address=?",new String[]{address},"date ASC");int n=0,total=0;if(c!=null){while(c.moveToNext()){total++;String body=c.getString(1);SmsAnalyzer.Result r=SmsAnalyzer.analyze(body);if(db.exists(body,c.getLong(2))){Toast.makeText(this,"⚠️ عملية مكررة: تم تجاهلها",Toast.LENGTH_SHORT).show();continue;} if(!r.error.isEmpty()){db.addReview(body,c.getLong(2),address,r.error);continue;} n+=db.add(new Transaction(0,r.type,r.party,r.reference,body,r.amount,r.smsBalance,c.getLong(2),"SMS - "+address))>0?1:0;}c.close();}selectedConversation=address;refresh();Toast.makeText(this,"تمت مراجعة "+total+" رسالة، واستيراد "+n+" عملية جديدة من "+address,Toast.LENGTH_LONG).show();}
 void scanAll(){Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"body","date","address"},null,null,"date ASC");int n=0;if(c!=null){while(c.moveToNext()){String body=c.getString(0);SmsAnalyzer.Result r=SmsAnalyzer.analyze(body);if(db.exists(body,c.getLong(1))){continue;} if(!r.error.isEmpty()){db.addReview(body,c.getLong(1),c.getString(2),r.error);continue;} n+=db.add(new Transaction(0,r.type,r.party,r.reference,body,r.amount,r.smsBalance,c.getLong(1),"SMS - "+c.getString(2)))>0?1:0;}c.close();}refresh();Toast.makeText(this,"تم استيراد "+n+" عملية جديدة",Toast.LENGTH_LONG).show();}
 void showTransaction(Transaction t){String date=new SimpleDateFormat("yyyy/MM/dd HH:mm:ss",Locale.getDefault()).format(new Date(t.time));String type=t.type.equals("credit")?"دائن / إيداع":"مدين / خصم";StringBuilder s=new StringBuilder();s.append("نوع العملية: ").append(type).append("\nالمبلغ: ").append(t.amount).append("\nالشخص / الجهة: ").append(t.party.isEmpty()?"غير محدد":t.party).append("\nرقم العملية: ").append(t.reference.isEmpty()?"غير موجود":t.reference).append("\nالتاريخ والوقت: ").append(date).append("\nالمصدر: ").append(t.source).append("\nالرصيد المحسوب: ").append(t.calculatedBalance).append("\n");if(t.smsBalance>0)s.append("رصيد الرسالة (مرجعي فقط): ").append(t.smsBalance).append("\n");s.append("\nنص الرسالة الكامل:\n").append(t.body);new AlertDialog.Builder(this).setTitle("تفاصيل العملية").setMessage(s.toString()).setPositiveButton("إغلاق",null).show();}\n void showReviews(){Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"address","body","date"},null,null,"date DESC");StringBuilder s=new StringBuilder();int n=0;if(c!=null){while(c.moveToNext()){SmsAnalyzer.Result r=SmsAnalyzer.analyze(c.getString(1));if(r.error.isEmpty())continue;n++;s.append("• المرسل: ").append(c.getString(0)).append("\n• السبب: ").append(r.error).append("\n• التاريخ: ").append(new SimpleDateFormat("yyyy/MM/dd HH:mm:ss",Locale.getDefault()).format(new Date(c.getLong(2)))).append("\n• النص: ").append(c.getString(1)).append("\n\n");}c.close();}if(n==0)s.append("لا توجد عمليات تحتاج مراجعة حالياً.");new AlertDialog.Builder(this).setTitle("⚠️ العمليات التي تحتاج مراجعة ("+n+")").setMessage(s.toString()).setPositiveButton("إغلاق",null).show();}\n void refresh(){list.removeAllViews();double bal=db.opening(),in=0,out=0;String filter=selectedConversation==null?null:"SMS - "+selectedConversation;for(Transaction t:db.all()){if(filter!=null&&!filter.equals(t.source))continue;if(t.type.equals("credit")){bal+=t.amount;in+=t.amount;}else{bal-=t.amount;out+=t.amount;}t.calculatedBalance=bal;String date=new SimpleDateFormat("yyyy/MM/dd HH:mm",Locale.getDefault()).format(new Date(t.time));String s=(t.type.equals("credit")?"دائن + ":"مدين - ")+t.amount+" | "+(t.party.isEmpty()?"بدون اسم":t.party)+"\n"+date+" | "+t.source+"\nالرصيد المحسوب: "+bal+(t.smsBalance>0?" | رصيد الرسالة: "+t.smsBalance:"");TextView row=tv(s,15);row.setOnClickListener(v->showTransaction(t));row.setBackgroundColor(0xfff7f7f7);list.addView(row);View line=new View(this);line.setBackgroundColor(0xffdddddd);list.addView(line,new LinearLayout.LayoutParams(-1,1));}balance.setText((selectedConversation==null?"الرصيد المحسوب: ":"رصيد المحادثة المحسوب: ")+bal);inOut.setText((selectedConversation==null?"":"المحادثة المحددة: "+selectedConversation+"\n")+"إجمالي الداخل: "+in+"   |   إجمالي الخارج: "+out);}
}
